name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run quality-check
        run: npm run quality-check
